# -*- coding: utf-8 -*-
"""RubricaDriver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1toV83s4SxqzcXgl7GScgHKzN6hdS-P
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/Progetto - Rubrica contatti

from contactsmanager import ContactsManager, Menu, Action

class Utility():
  """
  Classe statica di utility
  """
  Choices = [Action.Exit.name,
           Action.Load.name,
           Action.Save.name,
           Action.Add.name,
           Action.Edit.name,
           Action.Delete.name,
           Action.Print.name,
           ]

  def print_menu():
    print("\nPhonebook Menu:")
    for key in Utility.Choices:
      print(" > " + key)

  def get_choice(selector): # selector is string
    i = 0
    choice = Action.Null
    for ch in Utility.Choices:
      if ch == selector:
        choice = Action(i)
        break
      i += 1
    return choice

if __name__ == '__main__':
    contacts = ContactsManager()
    choice = Action.Null
    while choice != Action.Exit:
        Utility.print_menu()
        try:
            print("\n > Select menu choice:")
            choice = Action(Utility.get_choice(input(" >> ")))
            Menu.MainMenu(contacts, choice)
        except:
            print("Ops... something went wrong.")
            choice = Action.Null

